### ISSUE TITLE
服务者的的服务时间没有做限制

### ISSUE THREAD

**Issue by flaght** [mlgoogle/viossvc#44]
1、开始时间应当小于结束时间
2、前端需要设置开始时间不能小于8点结束时间不能大于晚上9点
![image](https://cloud.githubusercontent.com/assets/9654033/20863778/83cbd8d8-ba11-11e6-9d97-1199576f19ef.png)

**Comment by xiaomudegithub** [comment]
已领取
已修复
已PR
